[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "plant_puller"
version = "0.0.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--import-mode=importlib",
]
testpaths = [
    "tests"
]